/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.test;

import java.io.IOException;
import java.util.concurrent.TimeoutException;

import com.rabbitmq.client.Channel;
import com.rabbitmq.client.Connection;
import com.rabbitmq.client.ConnectionFactory;

public class App {
    private final static String EXCHANGE_NAME = "logs";

    public static void main(String[] args) throws IOException, TimeoutException {

        ConnectionFactory factory = new ConnectionFactory();
        factory.setHost("localhost");

        try(Connection connection = factory.newConnection(); 
        Channel channel = connection.createChannel()){
            
            channel.exchangeDeclare(EXCHANGE_NAME, "fanout");
            
            String message = "[INFO] test log";
            // channel.basicPublish("", QUEUE_NAME, null, message.getBytes());
            channel.basicPublish(EXCHANGE_NAME, "", null, message.getBytes());
            System.out.println("message sent"+ message);

        }
    }
}
