version: '3'

volumes:
  postgres_db: {}
  backend_db: {}

services : 
  db:
    image : postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
#      - ./dockerVolumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sample
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwer1234
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "80:8080"
#    command:
#      - /usr/local/tomcat/catalina.sh run
    volumes : 
      - backend_db:/usr/local/tomcat/files
#      - ./dockerVolumes/backend:/var/files