/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.test;

import java.io.IOException;
import java.util.concurrent.TimeoutException;

import com.rabbitmq.client.Channel;
import com.rabbitmq.client.Connection;
import com.rabbitmq.client.ConnectionFactory;

public class App {
    private final static String QUEUE_NAME = "work_queue";

    public static void main(String[] args) throws IOException, TimeoutException {

        ConnectionFactory factory = new ConnectionFactory();
        factory.setHost("localhost");

        try(Connection connection = factory.newConnection(); 
        Channel channel = connection.createChannel()){
            // channel대부분의 api 가지고있음
            // 보내기 전에 queue 생성해야함
            channel.queueDeclare(QUEUE_NAME, false, false, false, null);
            String message = "..........";
            channel.basicPublish("", QUEUE_NAME, null, message.getBytes());
            System.out.println("message sent"+ message);

        }
    }
}
